server:
  port: 9093

###起个名字作为服务名称(该服务注册到eureka注册中心的名称，比如商品服务)
spring:
  application:
    name: wangguan
###服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://zmhomecn:123456@127.0.0.1:9100/eureka
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    ###是否需要从eureka上检索服务
    fetch-registry: true


zuul:
  routes:
    shangpin:  ##商品服务
      path: /shangpin/**
      #url
      servicdid: shangpin
    dingdan:
      path: /dingdan/**
      #url
      serviceid: dingdan